using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Domain.appFacture
{
    public class AGR
    {
            public String ACCEPT_STATUS;
            public String ACCOUNT;
            public String ACCOUNT2;
            public String ADDRESS;
            public int ALLOCATION_KEY;
            public Double AMOUNT;
            public String APAR_ID;
            public String APAR_NAME;
            public String APAR_TYPE;
            public DateTime ARRIVAL_DATE;
            public Double ARRIVE_ID;
            public String ATT_1_ID;
            public String ATT_2_ID;
            public String ATT_3_ID;
            public String ATT_4_ID;
            public String ATT_5_ID;
            public String ATT_6_ID;
            public String ATT_7_ID;
            public String BANK_ACC_TYPE;
            public String BANK_ACCOUNT;
            public int BASE_AMOUNT;
            public int BASE_CURR;
            public String CLEARING_CODE;
            public String CLIENT;
            public String CLIENT_REF;
            public int COLLECTION;
            public String COMMITMENT;
            public String COMPLAINT;
            public int COMPRESS_FLAG;
            public String CONTRACT_ORDER;
            public Double CUR_AMOUNT;
            public String CURR_DOC;
            public String CURR_LICENCE;
            public String CURRENCY;
            public int DC_FLAG;
            public String DESCRIPTION;
            public String DIM_1;
            public String DIM_2;
            public String DIM_3;
            public String DIM_4;
            public String DIM_5;
            public String DIM_6;
            public String DIM_7;
            public DateTime DISC_DATE;
            public int DISC_PERCENT;
            public int DISCOUNT;
            public DateTime DUE_DATE;
            public int EXCH_RATE;
            public int EXCH_RATE2;
            public int EXCH_RATE3;
            public String EXT_INV_REF;
            public String EXT_REF;
            public String FACTOR_SHORT;
            public int FISCAL_YEAR;
            public int HEADER_FLAG;
            public String INT_STATUS;
            public String INTRULE_ID;
            public int INV_ARR_SEQ;
            public int IS_OPEN_POST;
            public String KID;
            public DateTime LAST_UPDATE;
            public int LINE_NO;
            public int NUMBER_1;
            public int ORDER_ID;
            public int PART_PAY_FLAG;
            public String PAY_CURRENCY;
            public int PAY_FLAG;
            public String PAY_METHOD;
            public int PAY_PLAN_ID;
            public int PAY_PLAN_ID_REF;
            public String PAY_TRANSFER;
            public int PERIOD;
            public int PERIOD_NO;
            public String PLACE;
            public int PO_FLAG;
            public String PROVINCE;
            public String PSEUDO_ID;
            public int REG_AMOUNT;
            public String REM_LEVEL;
            public String RESPONSIBLE;
            public int REV_PERIOD;
            public String REVERSE_FLAG;
            public String REVERSE_TYPE;
            public int SEQUENCE_NO;
            public int SEQUENCE_REF;
            public int SEQUENCE_REF2;
            public String STATUS;
            public int STOP_TRIG;
            public String SWIFT;
            public int TAX_AMEND_FLAG;
            public String TAX_CODE;
            public int TAX_ID;
            public int TAX_SEQ_REF;
            public int TEMPLATE_ID;
            public String TAX_SYSTEM;
            public String TEMPLATE_TYPE;
            public String TERMS_ID;
            public DateTime TRANS_DATE;
            public int TRANS_ID;
            public String TRANS_TYPE;
            public String TREAT_CODE;
            public String USER_ID;
            public int VALUE_1;
            public int VALUE_2;
            public int VALUE_3;
            public int VAT_AMOUNT;
            public String VAT_REG_NO;
            public String VOUCH_STAT;
            public DateTime VOUCHER_DATE;
            public Int64 VOUCHER_NO;
            public int VOUCHER_REF;
            public int VOUCHER_REF2;
            public String VOUCHER_TYPE;
            public String WF_STATE;
            public String ZIP_CODE ;
            public String AUTH_CODE ;
            public int BASE_VALUE_2 ;
            public int BASE_VALUE_3  ;  
            public String CONTRACT_ID ;   
            public int ORIG_REFERENCE  ;
            public int IDFACTURE;
            public int NOLOT;
            public AGR() 
            {
                this.ACCEPT_STATUS = "";
                this.ACCOUNT = "";
                this.ACCOUNT2 = "";
                this.ADDRESS = "";
                this.ALLOCATION_KEY = 0;
                this.AMOUNT = 0;
                this.APAR_ID = "";
                this.APAR_NAME = "";
                this.APAR_TYPE = "";
                this.ARRIVAL_DATE = Convert.ToDateTime("01/01/2000");
                this.ARRIVE_ID = 0;
                /*this.ATT_1_ID = "0P";
                this.ATT_2_ID = "0O";
                this.ATT_4_ID = "0G";*/


            }
    }
}
