//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.appFacture
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTENSEIGNE
    {
        public FACTENSEIGNE()
        {
            this.FACTASSOGFACTTYPEENSEIGNE = new HashSet<FACTASSOGFACTTYPEENSEIGNE>();
            this.FACTSITE = new HashSet<FACTSITE>();
            this.OTOPACHETEUR = new HashSet<OTOPACHETEUR>();
            this.OTOPVENDEUR = new HashSet<OTOPVENDEUR>();
        }
    
        public int IDENSEIGNE { get; set; }
        public string LIBELLEENSEIGNE { get; set; }
        public Nullable<int> DERNIERUTILISATEUR { get; set; }
        public Nullable<System.DateTime> DATECREATION { get; set; }
        public Nullable<System.DateTime> DATEMODIFICATION { get; set; }
        public string CODE { get; set; }
        public string LOGO { get; set; }
        public string ICE { get; set; }
        public string PLINE1 { get; set; }
        public string PLINE2 { get; set; }
        public string PLINE3 { get; set; }
        public string PLINE4 { get; set; }
    
        public virtual ICollection<FACTASSOGFACTTYPEENSEIGNE> FACTASSOGFACTTYPEENSEIGNE { get; set; }
        public virtual ICollection<FACTSITE> FACTSITE { get; set; }
        public virtual ICollection<OTOPACHETEUR> OTOPACHETEUR { get; set; }
        public virtual ICollection<OTOPVENDEUR> OTOPVENDEUR { get; set; }
    }
}
