//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.appFacture
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTDEMANDE
    {
        public FACTDEMANDE()
        {
            this.FACTDEMANDEDETAIL = new HashSet<FACTDEMANDEDETAIL>();
            this.FACTFACTURE = new HashSet<FACTFACTURE>();
            this.FACTPIECEJOINTE = new HashSet<FACTPIECEJOINTE>();
        }
    
        public int IDDEMANDE { get; set; }
        public string REFERENCEFACT { get; set; }
        public string LIBELLEDEMANDE { get; set; }
        public string CHAPITRE { get; set; }
        public Nullable<int> IDFACTTYPE { get; set; }
        public Nullable<short> STATUS { get; set; }
        public Nullable<decimal> MNTHT { get; set; }
        public Nullable<decimal> MNTTVA { get; set; }
        public Nullable<decimal> MNTTTC { get; set; }
        public Nullable<int> IDSITE { get; set; }
        public Nullable<short> TYPECLIENT { get; set; }
        public Nullable<int> IDCLIENT { get; set; }
        public Nullable<int> IDCLIENTINTERNE { get; set; }
        public string COMMENTAIRE { get; set; }
        public Nullable<int> DERNIERUTILISATEUR { get; set; }
        public Nullable<System.DateTime> DATECREATION { get; set; }
        public Nullable<System.DateTime> DATEMODIFICATION { get; set; }
        public Nullable<System.DateTime> DATEREFUS { get; set; }
        public Nullable<System.DateTime> DATEVALIDATION { get; set; }
        public Nullable<System.DateTime> DATEIMPRESSION { get; set; }
        public Nullable<System.DateTime> DATECOMPTABILISATION { get; set; }
        public string ANNEEPRESTATION { get; set; }
        public Nullable<short> FLAGAVOIR { get; set; }
        public string CNUFVENDEUR { get; set; }
        public string CNUFACHETEUR { get; set; }
        public Nullable<short> RAYON { get; set; }
        public Nullable<short> RAYONACHETEUR { get; set; }
        public Nullable<decimal> TAUXTVA { get; set; }
        public Nullable<decimal> MNTTVAIPPRF { get; set; }
        public Nullable<decimal> TAUXTVAIPPRF { get; set; }
    
        public virtual FACTCLIENT FACTCLIENT { get; set; }
        public virtual ICollection<FACTDEMANDEDETAIL> FACTDEMANDEDETAIL { get; set; }
        public virtual FACTSITE FACTSITE { get; set; }
        public virtual FACTSITE FACTSITE1 { get; set; }
        public virtual FACTTYPE FACTTYPE { get; set; }
        public virtual FACTTYPECLIENT FACTTYPECLIENT { get; set; }
        public virtual ICollection<FACTFACTURE> FACTFACTURE { get; set; }
        public virtual ICollection<FACTPIECEJOINTE> FACTPIECEJOINTE { get; set; }
        public virtual FACTDEMANDESTATUS FACTDEMANDESTATUS { get; set; }
    }
}
