//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.appFacture
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTDEMANDEDETAIL
    {
        public int IDDEMANDEDET { get; set; }
        public int IDDEMANDE { get; set; }
        public string REFERENCEPRODUIT { get; set; }
        public string LIBELLEPRODUIT { get; set; }
        public Nullable<decimal> QUANTITE { get; set; }
        public Nullable<decimal> TAUXTVA { get; set; }
        public Nullable<decimal> PRIXUNITAIRE { get; set; }
        public Nullable<decimal> MNTTVA { get; set; }
        public Nullable<decimal> MNTHT { get; set; }
        public Nullable<decimal> MNTTTC { get; set; }
        public Nullable<int> DERNIERUTILISATEUR { get; set; }
        public Nullable<System.DateTime> DATECREATION { get; set; }
        public Nullable<System.DateTime> DATEMODIFICATION { get; set; }
        public Nullable<decimal> TTVAIPPRF { get; set; }
        public Nullable<decimal> MNTTVAIPPRF { get; set; }
    
        public virtual FACTDEMANDE FACTDEMANDE { get; set; }
    }
}
