//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.appFacture
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTFACTURESTATUS
    {
        public FACTFACTURESTATUS()
        {
            this.FACTFACTURE = new HashSet<FACTFACTURE>();
            this.OTOPFACTURE = new HashSet<OTOPFACTURE>();
        }
    
        public short STATUS { get; set; }
        public string LIBELLE { get; set; }
        public Nullable<int> DERNIERUTILISATEUR { get; set; }
        public Nullable<System.DateTime> DATECREATION { get; set; }
        public Nullable<System.DateTime> DATEMODIFICATION { get; set; }
    
        public virtual ICollection<FACTFACTURE> FACTFACTURE { get; set; }
        public virtual ICollection<OTOPFACTURE> OTOPFACTURE { get; set; }
    }
}
