//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.appFacture
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTFACTPIECEJOINTE
    {
        public int IDPIECEJOINTE { get; set; }
        public int IDFACTURE { get; set; }
        public string NOM { get; set; }
        public string NOMINTERNE { get; set; }
        public string CONTENTTYPE { get; set; }
        public Nullable<int> DERNIERUTILISATEUR { get; set; }
        public Nullable<System.DateTime> DATECREATION { get; set; }
        public Nullable<System.DateTime> DATEMODIFICATION { get; set; }
    
        public virtual FACTFACTURE FACTFACTURE { get; set; }
    }
}
