//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.appFacture
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTGROUPE
    {
        public FACTGROUPE()
        {
            this.FACTINTERFACE = new HashSet<FACTINTERFACE>();
            this.FACTUSER = new HashSet<FACTUSER>();
        }
    
        public int IDGROUPE { get; set; }
        public string LIBELLEGROUPE { get; set; }
    
        public virtual ICollection<FACTINTERFACE> FACTINTERFACE { get; set; }
        public virtual ICollection<FACTUSER> FACTUSER { get; set; }
    }
}
