//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.appFacture
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTOPACRTRANS
    {
        public string ACCEPT_STATUS { get; set; }
        public string ACCOUNT { get; set; }
        public string ACCOUNT2 { get; set; }
        public string ADDRESS { get; set; }
        public short ALLOCATION_KEY { get; set; }
        public decimal AMOUNT { get; set; }
        public string APAR_ID { get; set; }
        public string APAR_NAME { get; set; }
        public string APAR_TYPE { get; set; }
        public System.DateTime ARRIVAL_DATE { get; set; }
        public decimal ARRIVE_ID { get; set; }
        public string ATT_1_ID { get; set; }
        public string ATT_2_ID { get; set; }
        public string ATT_3_ID { get; set; }
        public string ATT_4_ID { get; set; }
        public string ATT_5_ID { get; set; }
        public string ATT_6_ID { get; set; }
        public string ATT_7_ID { get; set; }
        public string BANK_ACC_TYPE { get; set; }
        public string BANK_ACCOUNT { get; set; }
        public decimal BASE_AMOUNT { get; set; }
        public decimal BASE_CURR { get; set; }
        public string CLEARING_CODE { get; set; }
        public string CLIENT { get; set; }
        public string CLIENT_REF { get; set; }
        public short COLLECTION { get; set; }
        public string COMMITMENT { get; set; }
        public string COMPLAINT { get; set; }
        public short COMPRESS_FLAG { get; set; }
        public string CONTRACT_ORDER { get; set; }
        public decimal CUR_AMOUNT { get; set; }
        public string CURR_DOC { get; set; }
        public string CURR_LICENCE { get; set; }
        public string CURRENCY { get; set; }
        public short DC_FLAG { get; set; }
        public string DESCRIPTION { get; set; }
        public string DIM_1 { get; set; }
        public string DIM_2 { get; set; }
        public string DIM_3 { get; set; }
        public string DIM_4 { get; set; }
        public string DIM_5 { get; set; }
        public string DIM_6 { get; set; }
        public string DIM_7 { get; set; }
        public System.DateTime DISC_DATE { get; set; }
        public decimal DISC_PERCENT { get; set; }
        public decimal DISCOUNT { get; set; }
        public System.DateTime DUE_DATE { get; set; }
        public decimal EXCH_RATE { get; set; }
        public decimal EXCH_RATE2 { get; set; }
        public decimal EXCH_RATE3 { get; set; }
        public string EXT_INV_REF { get; set; }
        public string EXT_REF { get; set; }
        public string FACTOR_SHORT { get; set; }
        public long FISCAL_YEAR { get; set; }
        public short HEADER_FLAG { get; set; }
        public string INT_STATUS { get; set; }
        public string INTRULE_ID { get; set; }
        public long INV_ARR_SEQ { get; set; }
        public short IS_OPEN_POST { get; set; }
        public string KID { get; set; }
        public System.DateTime LAST_UPDATE { get; set; }
        public long LINE_NO { get; set; }
        public long NUMBER_1 { get; set; }
        public decimal ORDER_ID { get; set; }
        public short PART_PAY_FLAG { get; set; }
        public string PAY_CURRENCY { get; set; }
        public short PAY_FLAG { get; set; }
        public string PAY_METHOD { get; set; }
        public decimal PAY_PLAN_ID { get; set; }
        public decimal PAY_PLAN_ID_REF { get; set; }
        public string PAY_TRANSFER { get; set; }
        public long PERIOD { get; set; }
        public short PERIOD_NO { get; set; }
        public string PLACE { get; set; }
        public long PO_FLAG { get; set; }
        public string PROVINCE { get; set; }
        public string PSEUDO_ID { get; set; }
        public decimal REG_AMOUNT { get; set; }
        public string REM_LEVEL { get; set; }
        public string RESPONSIBLE { get; set; }
        public long REV_PERIOD { get; set; }
        public string REVERSE_FLAG { get; set; }
        public string REVERSE_TYPE { get; set; }
        public long SEQUENCE_NO { get; set; }
        public long SEQUENCE_REF { get; set; }
        public long SEQUENCE_REF2 { get; set; }
        public string STATUS { get; set; }
        public long STOP_TRIG { get; set; }
        public string SWIFT { get; set; }
        public short TAX_AMEND_FLAG { get; set; }
        public string TAX_CODE { get; set; }
        public short TAX_ID { get; set; }
        public long TAX_SEQ_REF { get; set; }
        public long TEMPLATE_ID { get; set; }
        public string TAX_SYSTEM { get; set; }
        public string TEMPLATE_TYPE { get; set; }
        public string TERMS_ID { get; set; }
        public System.DateTime TRANS_DATE { get; set; }
        public decimal TRANS_ID { get; set; }
        public string TRANS_TYPE { get; set; }
        public string TREAT_CODE { get; set; }
        public string USER_ID { get; set; }
        public decimal VALUE_1 { get; set; }
        public decimal VALUE_2 { get; set; }
        public decimal VALUE_3 { get; set; }
        public decimal VAT_AMOUNT { get; set; }
        public string VAT_REG_NO { get; set; }
        public string VOUCH_STAT { get; set; }
        public System.DateTime VOUCHER_DATE { get; set; }
        public decimal VOUCHER_NO { get; set; }
        public decimal VOUCHER_REF { get; set; }
        public decimal VOUCHER_REF2 { get; set; }
        public string VOUCHER_TYPE { get; set; }
        public string WF_STATE { get; set; }
        public string ZIP_CODE { get; set; }
        public string AUTH_CODE { get; set; }
        public decimal BASE_VALUE_2 { get; set; }
        public decimal BASE_VALUE_3 { get; set; }
        public string CONTRACT_ID { get; set; }
        public decimal ORIG_REFERENCE { get; set; }
        public Nullable<int> IDFACTURE { get; set; }
        public int IDACRTRANS { get; set; }
        public Nullable<int> NOLOT { get; set; }
    }
}
