//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.appFacture
{
    using System;
    using System.Collections.Generic;
    
    public partial class OTOPVENDEUR
    {
        public OTOPVENDEUR()
        {
            this.OTOPFACTURE = new HashSet<OTOPFACTURE>();
        }
    
        public int IDVENDEUR { get; set; }
        public string LIBELLESITE { get; set; }
        public Nullable<short> VENDBA { get; set; }
        public Nullable<int> DERNIERUTILISATEUR { get; set; }
        public Nullable<System.DateTime> DATECREATION { get; set; }
        public Nullable<System.DateTime> DATEMODIFICATION { get; set; }
        public Nullable<int> IDENSEIGNE { get; set; }
        public string IP { get; set; }
        public Nullable<int> CODEGOLD { get; set; }
        public string CODEAGRESSO { get; set; }
        public string ADRLINE1 { get; set; }
        public Nullable<System.DateTime> DATEDERNIEREEXECUTION { get; set; }
        public string ADRLINE2 { get; set; }
        public string ADRLINE3 { get; set; }
        public string CNUF { get; set; }
    
        public virtual FACTENSEIGNE FACTENSEIGNE { get; set; }
        public virtual ICollection<OTOPFACTURE> OTOPFACTURE { get; set; }
    }
}
